name: macos


on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    env:
      OPENSCAD_LIBRARIES: /Users/runner/work/actions-test/libraries/install/
    steps:
    - name: Checkout
      uses: actions/checkout@v2
#    - name: Setup upterm session
#      uses: lhotari/action-upterm@v1
    - name: Cache Libraries
      id: cache-libraries
      uses: actions/cache@v2
      with:
        path: ${{ env.OPENSCAD_LIBRARIES }}
        key: ${{ runner.os }}-libraries2-${{ hashFiles('macosx-build-dependencies.sh') }}
        restore-keys: ${{ runner.os }}-libraries2-
    - name: Build
      run: |
        echo "PWD = $CI_BASEDIR"
        echo "PATH = $PATH"
        export PKG_CONFIG_PATH="$OPENSCAD_LIBRARIES/lib/pkgconfig"
        export DYLD_LIBRARY_PATH="$OPENSCAD_LIBRARIES/lib"
        export DYLD_FRAMEWORK_PATH="$OPENSCAD_LIBRARIES/lib"
        echo "DYLD_LIBRARY_PATH: $DYLD_LIBRARY_PATH"
        ./scripts/macosx-build-dependencies.sh double_conversion
        ./scripts/macosx-build-dependencies.sh eigen
        ./scripts/macosx-build-dependencies.sh gmp
        ./scripts/macosx-build-dependencies.sh mpfr
        ./scripts/macosx-build-dependencies.sh glew
        ./scripts/macosx-build-dependencies.sh gettext
        ./scripts/macosx-build-dependencies.sh libffi
        ./scripts/macosx-build-dependencies.sh freetype
        ./scripts/macosx-build-dependencies.sh ragel
        ./scripts/macosx-build-dependencies.sh harfbuzz
        ./scripts/macosx-build-dependencies.sh libxml2
        ./scripts/macosx-build-dependencies.sh fontconfig || true
        mkdir -p ${{ runner.temp }}/out
        tar cz -C "$OPENSCAD_LIBRARIES" -f ${{ runner.temp }}/out/libraries.tar.gz .
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: Build Artifacts
        path: ${{ runner.temp }}/out
