name: macos

on:
  push:
    branches:
      - main
  pull_request:

env:
  OPENSCAD_LIBRARIES=$RUNNER_WORKSPACE/libraries/install/

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache Libraries
      id: cache-libraries
      uses: actions/cache@v2
      with:
        path: $OPENSCAD_LIBRARIES
        key: "${{ runner.os }}-libraries"
     - name: Build
      run: |
        echo "PWD = $CI_BASEDIR"
        echo "PATH = $PATH"
        export PKG_CONFIG_PATH="$OPENSCAD_LIBRARIES/lib/pkgconfig"
        export DYLD_LIBRARY_PATH="$OPENSCAD_LIBRARIES/lib"
        export DYLD_FRAMEWORK_PATH="$OPENSCAD_LIBRARIES/lib"
        echo "DYLD_LIBRARY_PATH: $DYLD_LIBRARY_PATH"
        ./macosx-build-dependencies.sh libzip
        tar cz -C "$OPENSCAD_LIBRARIES" -f ${{ runner.temp }}/libraries.tar.gz .
#    - name: Setup upterm session
#      uses: lhotari/action-upterm@v1
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: Build Artifacts
        path: ${{ runner.temp }}
