name: macos

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup upterm session
      uses: lhotari/action-upterm@v1
    - name: Build
      run: |
        echo "PWD = $CI_BASEDIR"
        echo "PATH = $PATH"
        export OPENSCAD_LIBRARIES=/Users/runner/work/libraries/install/
        mkdir -p "$OPENSCAD_LIBRARIES"
        export PKG_CONFIG_PATH="$OPENSCAD_LIBRARIES/lib/pkgconfig"
        export DYLD_LIBRARY_PATH="$OPENSCAD_LIBRARIES/lib"
        export DYLD_FRAMEWORK_PATH="$OPENSCAD_LIBRARIES/lib"
        echo "DYLD_LIBRARY_PATH: $DYLD_LIBRARY_PATH"
        ./macosx-build-dependencies.sh libzip
        tar -cz -C "$OPENSCAD_LIBRARIES" -f /tmp/out/libraries.tar.gz .
